apiVersion: v1
kind: ServiceAccount
metadata:
  name: k6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
      - name: k6
        image: loadimpact/k6
        command: ["tail","-f","/dev/null"]